version: '3.8'
services:
  product-ws:
    image: product-ws-local:latest
    container_name: product-ws
    environment:
      DB_PASSWORD: guest
      DB_URL: jdbc:postgresql://host.docker.internal:5432/product
      DB_USERNAME: guest
      DLL_AUTO: none # this will not alter the state of the database. At first startup set it to 'create' to generate database schema.
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: product
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
